add code for later to avoiding multiple simultaneous deployments

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -133,12 +133,32 @@ jobs:
 
       - name: Deploy to AWS CodeDeploy
         run: |
-          aws deploy create-deployment \
+          DEPLOYMENT_ID=$(aws deploy create-deployment \
             --application-name tournamaths-app \
             --deployment-config-name CodeDeployDefault.OneAtATime \
             --deployment-group-name tournamaths-deployment-group \
             --description "TournaMaths deployment" \
-            --s3-location bucket=tournamaths,bundleType=zip,key=tournamaths-deployment.zip
+            --s3-location bucket=tournamaths,bundleType=zip,key=tournamaths-deployment.zip \
+            --query 'deploymentId' --output text)
+
+          echo "Deployment ID: $DEPLOYMENT_ID"
+
+          # TODO = uncomment this when doing deployments less regularly (so chew up fewer Github Actions minutes)
+          # Poll the deployment status, so don't try to accidentally run multiple deployments at once
+          #while true; do
+          #  STATUS=$(aws deploy get-deployment \
+          #    --deployment-id $DEPLOYMENT_ID \
+          #    --query 'deploymentInfo.status' --output text)
+
+          #  echo "Deployment Status: $STATUS"
+
+          #  if [[ $STATUS == "Succeeded" ]]; then
+          #    break
+          #  elif [[ "$STATUS" == "Failed" || "$STATUS" == "Stopped" ]]; then
+          #    exit 1
+          #  fi
+          #  sleep 10
+          #done
 
       - name: Update commit status
         if: always()
